### PR TITLE
Rubocop warning fixes

### PR DESCRIPTION
**Pull request by guilhem**
From https://github.com/redguide/nodejs/blob/master/.rubocop.yml

### CODE REVIEW

**Comment by fonsecas72** [comment]
This does not seem to affect anything, Am I wrong?
But I would like to add consistency between projects.
For what I'm used to see, I would only change the vendor's igore to
```ruby
 - 'vendor/**/*'
```

**Comment by guilhem** [comment]
@fonsecas72 problems seems to appear here: https://travis-ci.org/redguide/locales/jobs/53025883

**Comment by fonsecas72** [comment]
It looks like only the vendor's dir exclusion is deprecated and that's why I would not change the other files exclusion because I usually see file exclusion as they were.
I'de say, let's choose one way or another and apply it to all cookbooks.

**Comment by guilhem** [comment]
@fonsecas72 include as it's done in this patch is cool for test-cookbooks that can be in `test` directory.
But it's obviously not a major things.

Let me know what people are thinking and I will change my commit :)

**Comment by guilhem** [comment]
oh and also @fonsecas72 there is no problem to me if 2 teams of maintainers don't want same syntax or behavior.
What I only want is discussions, examples and contributions between each other :) (and I'm sure the better will won at the end by "success story" ;))

"big bang" changes have too many chances to fail and to freeze any new way of thinking ^^

**Comment by BarthV** [comment]
Hi,
Best practice for excluding vendor dir is definitely ```'vendor/**/*'```
I strongly recommend to merge this PR since it's widely accepted + it cast many warnings in Travis.

Even Rubocop itself uses this syntax :
https://github.com/bbatsov/rubocop/blob/master/.rubocop.yml#L7

So :+1: 

Please have a look :
- http://caseywest.com/faster-ci-on-travis-and-docker-for-ruby-and-rails-and-rubocop/
- https://github.com/bbatsov/rubocop/blob/master/.rubocop.yml
- https://github.com/bbatsov/rubocop/issues/1427
- https://www.google.fr/#q=rubocop+exclude+vendor+dir

**Comment by BarthV** [comment]
Using test cookbooks can be very useful in the future, if feel the to add some QA/tests.
:+1: for this PR syntax

**Comment by fonsecas72** [comment]
> Using test cookbooks can be very useful in the future
I don't know how this can become handy yet, so :+1: to learn. ;-)

**Pull request merged**
